---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake
spec:
  provider:
    fake:
      data:
      - key: "/global/grafana-cloud"
        valueMap:
          env: global
          service: grafana-cloud
      - key: "/prod/fake"
        valueMap:
          env: prod
          service: fake
      - key: "/dev/fake"
        valueMap:
          env: dev
          service: fake