---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api
  namespace: external-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: api
  dataFrom:
  - extract:
      key: /global/grafana-cloud