---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  targetNamespace: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: '1.9.1'
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      interval: 1m
  values:
    installCRDs: false